from accounts.freelance_views.overview import FreelanceOverview
from accounts.freelance_views.freelance import Freelance,FreelanceFull,FreelanceWalletView
from accounts.freelance_views.freelance_student import FreelanceStudent,FreelanceStudentMultiple,FreelanceStudentItem